### PR TITLE
Feature/custom sources and layers

### LINKED ISSUE #19: Add WMS layer support
@henhuy I intend to include external WMS layers in apps, this is [supported by maplibre](https://maplibre.org/maplibre-gl-js/docs/examples/wms/). How much work is this feature?

Example: [Flurstücke BRB](https://isk.geobasis-bb.de/ows/alkis_wms?request=GetCapabilities&service=WMS)

### PR DESCRIPTION
**Pull request by nesnoj**
Closes #19 

I added some text to the layers readme. Please adjust if needed.

Todos:
- [x] The layer control should be included in the "normal" layer list at a configurable position
- [ ] Add symbol such as 
image
 (best would be custom icons #16)

### CODE REVIEW

**Comment by nesnoj** [comment]
Ups, wrong base? Please adjust if needed @henhuy

**Comment by nesnoj** [comment]
We can postpone the symbol stuff and handle it in #16

**Comment by nesnoj** [comment]
Currently it is not possible to have the layers from `MAP_ENGINE_LAYERS` in the background, [here](https://github.com/rl-institut/django-mapengine/blob/60dadce81d79a3c449f83ca0aa8b9e5c0b962c29/django_mapengine/layers.py#L245-L261) the layer order can be only defined within one group (static, cluster, MAP_ENGINE_LAYERS) but the group order is predefined. I changed it to have external layers in the background,  if you are fine with this we're done and this one can be merged.

(A configurable group order would be good, will open an extra issue)

**Comment by henhuy** [comment]
> It was not possible to have the layers from `MAP_ENGINE_LAYERS` in the background, [with this code](https://github.com/rl-institut/django-mapengine/blob/60dadce81d79a3c449f83ca0aa8b9e5c0b962c29/django_mapengine/layers.py#L245-L261) the layer order can be only defined within one group (static, cluster, MAP_ENGINE_LAYERS) but the group order is predefined. I changed it in [aaa14a3](https://github.com/rl-institut/django-mapengine/commit/aaa14a3f23313ffaa0997a114d78f83f19803a91) to have external layers in the background, if you are fine with this we're done and this one can be merged.
> 
> (A configurable group order would be good #22)

For now this is fine. And you already opened a new ticket for this feature (which currently can be solved in a workaround in [MapEngineMixin](https://github.com/rl-institut/django-mapengine/blob/be6ca8c1ad98912d8389c9b2c0fff95969e4e39a/django_mapengine/views.py#L23) but you are right - there should be a documented option for this.
So I will merge.

**Pull request merged**
