### PR TITLE
legend label and unit

### PR DESCRIPTION
**Pull request by Josephine-Marie**
Waits for #3 

get legend label and unit from setup in respective project settings
MAP_ENGINE_CHOROPLETHS

### CODE REVIEW

**Comment by Josephine-Marie** [comment]
@henhuy that's how you meant it, right?

**Comment by Josephine-Marie** [comment]
there is a naming inconsistency in #3: in setup.Choropleth it is called "name" and "label" and in the PR it is called "identifier" and "name"

**Comment by henhuy** [comment]
> @henhuy that's how you meant it, right?

Yes. And the handling of title and unit must be implemented in mapengine JS as well.
So that change in digiplan is only to add title and unit for each choropleth.

**Comment by henhuy** [comment]
Ah , I see - once #3 is merged, this PR works. Okay thanks!

**Pull request merged**
